<?php
    session_start();
?>
<?php
    if(isset($_SESSION["name"]))
    {
        session_unset();
        session_destroy();
        header("Location:../Pages/home.php");
    }
    else
    {
        header("Location:../Pages/loginform.php");
    }
?>